# SOPS configuration for encrypting secrets
# This file defines which keys can decrypt which secrets

# To get your age public key, run:
#   age-keygen -y ~/.config/sops/age/keys.txt

creation_rules:
  # Default rule - encrypt with your age key
  - path_regex: secrets\.yaml$
    age: >-
      YOUR_AGE_PUBLIC_KEY_HERE
